--[============================================================[                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
  `RW`  = Read-Write (editable) variable                                                                                                                                                                                                                             
  `RO`  = Read-Only variable                                                                                                                                                                                                                                         
  `>>>` = Example usage                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                     
**** variables                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                     
  ** Stake                                                                                                                                                                                                                                                           
      apikey             : string : RW  [required]                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                     
      mirror             : string : RW  [optional]                                                                                                                                                                                                                   
      cookie             : string : RW  [optional]                                                                                                                                                                                                                   
      user_agent         : string : RW  [optional]                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                     
  basebet            : float  : RW  [required]                                                                                                                                                                                                                       
  currency           : string : RW  [required]                                                                                                                                                                                                                       
  nextbet            : float  : RW  [required]                                                                                                                                                                                                                       
  target             :        : RW  [required]                                                                                                                                                                                                                       
                    ** float (single target),                                                                                                                                                                                                                        
                       >>> target = 37.89                                                                                                                                                                                                                            
                    ** table (random target between low-high),                                                                                                                                                                                                       
                       >>> target = {low = 37, high = 37.89}                                                                                                                                                                                                         
                    ** or, you can retrieve them using dot (.) notation.                                                                                                                                                                                             
                       >>> target.low                                                                                                                                                                                                                                
                       >>> target.high                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                     
               **NOTE: you must fill this variable with MULTIPLIER-TARGET, not WIN-CHANCE!!                                                                                                                                                                          
                       ** If you want to use chance, I have made an example function to convert chance to target. You can find it below.                                                                                                                             
                                                                                                                                                                                                                                                                     
  maxbet             : float  : RW  [optional]                                                                                                                                                                                                                       
  replay             : bool   : RW  [optional, default: false]                                                                                                                                                                                                       
  resetIfLose        : float  : RW  [optional]                                                                                                                                                                                                                       
  resetIfProfit      : float  : RW  [optional]                                                                                                                                                                                                                       
  resetIfLoseStreak  : int    : RW  [optional]                                                                                                                                                                                                                       
  resetIfWinStreak   : int    : RW  [optional]                                                                                                                                                                                                                       
  targetBalance      : float  : RW  [optional]                                                                                                                                                                                                                       
  targetLose         : float  : RW  [optional]                                                                                                                                                                                                                       
  targetProfit       : float  : RW  [optional]                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                     
  balance            : float  : RO                                                                                                                                                                                                                                   
  bets               : int    : RO                                                                                                                                                                                                                                   
  broker             : string : RO : broker-name                                                                                                                                                                                                                     
  currentstreak      : int    : RO                                                                                                                                                                                                                                   
                    ** currentstreak is a positive or negative integer. Will be positive when you `win` and negative when you `lose`.                                                                                                                                
                                                                                                                                                                                                                                                                     
  lastBet            : table  : RO                                                                                                                                                                                                                                   
                    ** This is an object containing more details about the previous bet, including:                                                                                                                                                                  
                       ** amount    : float  :                                                                                                                                                                                                                       
                       ** target    : float  :                                                                                                                                                                                                                       
                       ** profit    : float  : profit for the last bet made. This is not the total profit (betting 1 unit at x2 payout, when winning, profit will show 1 (returned = 2), when losing, profit will show -1).                                          
                       ** result    : float  : lucky number                                                                                                                                                                                                          
                    ** you can retrieve them using dot (.) notation.                                                                                                                                                                                                 
                       >>> lastBet.target                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                     
  losses             : int    : RO                                                                                                                                                                                                                                   
  previousbet        : float  : RO                                                                                                                                                                                                                                   
  profit             : float  : RO                                                                                                                                                                                                                                   
  win                : bool   : RO                                                                                                                                                                                                                                   
  wins               : int    : RO                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                     
  isFirstGreen              : bool : RO                                                                                                                                                                                                                              
  isFirstRed                : bool : RO                                                                                                                                                                                                                              
  isMaxBetReached           : bool : RO                                                                                                                                                                                                                              
  isResetWinStreakReached   : bool : RO                                                                                                                                                                                                                              
  isResetLoseStreakReached  : bool : RO                                                                                                                                                                                                                              
  isResetProfitReached      : bool : RO                                                                                                                                                                                                                              
  isResetLossReached        : bool : RO                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
**** functions                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                     
  dobet()              : your logic here                                                                                                                                                                                                                             
  stop()               : kill the bot                                                                                                                                                                                                                                
  resetseed(seed)      :                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                     
             ** resetseed require `seed` parameter, if seed is not specified, the bot will automatically generate a random seed for you.                                                                                                                             
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
--]============================================================]                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
--[=============[                                                                                                                                                                                                                                                    
     EXAMPLE!!                                                                                                                                                                                                                                                       
--]=============]                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
function chance_to_target(chance)                                                                                                                                                                                                                                    
    if broker:lower() == "stake" then                                                                                                                                                                                                                                
        div = 99                                                                                                                                                                                                                                                     
    elseif broker:lower() == "pasino" then                                                                                                                                                                                                                           
        div = 97                                                                                                                                                                                                                                                     
    end                                                                                                                                                                                                                                                              
    return tonumber(string.format("%.2f", (div/chance)))                                                                                                                                                                                                             
end                                                                                                                                                                                                                                                                  
-- call this function with `chance_to_target(your_chance)`. e.g:                                                                                                                                                                                                     
-- target = chance_to_target(3.78)                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                     
function fibonacci(level)                                                                                                                                                                                                                                            
    local _start, _next = 0, 1                                                                                                                                                                                                                                       
    if level <= 0 then                                                                                                                                                                                                                                               
        return basebet                                                                                                                                                                                                                                               
    end                                                                                                                                                                                                                                                              
    for i = 1, level do                                                                                                                                                                                                                                              
        _start, _next = _next, _start + _next                                                                                                                                                                                                                        
    end                                                                                                                                                                                                                                                              
    return _start * basebet                                                                                                                                                                                                                                          
end

apikey = "6676696e47f3c93327ec1a4aacf98697f565fcccf4ed0438a93c63f755c5c8252443defba037458fb5270492dc018264"
                                                                                                                            
currency = "usdt"                                                         
chance= 1.07
base= 0.00000000
bethigh = true
randomHighLow = false
multiplier = 1
nextbet = base  
curbet = base
basemultiplier = 0.00075
function dobet()
base= (balance - (profit * 3)) * basemultiplier 
chance = 1.07 + (currentstreak * (basemultiplier * 1.3))

if win then
	nextbet = previousbet* multiplier
	if currentstreak%5 then
	nextbet = base
	end
    else
        if currentstreak==-6 then
         curbet = base
        else
          curbet = base
        end
        nextbet = base
    end

if (randomHighLow) then
  if (math.random() < .1137) then bethigh = !bethigh end
  end
  end